### ISSUE TITLE
The offical site has worng alert when visit the `FullScroll` page.

### ISSUE THREAD

**Issue by sadofriod** [lengyibai/code-snippet#3]
When I open the [link](https://lengyibai.github.io/lib/docs/Components/statics/FullScroll.html), it will open a alert. And rolling to page bottom , the same alert will be shown. 

https://github.com/lengyibai/code-lib/assets/23006024/486ea578-8e39-4235-be14-5a2955bc2d71

**Comment by lengyibai** [comment]
你在滚动回调的演示里滚动，产生的alert
